library(Seurat)
library(cowplot)
KO.data <- Read10X(data.dir = "D:/Jmjd1c_Treg_Tumor/single_cell_RNAseq/201692_20210126_1_foxp3jmjd1c_mc205_tumour_wt_ko_treg/Treg_KO/outs/filtered_feature_bc_matrix")
WT.data <- Read10X(data.dir = "D:/Jmjd1c_Treg_Tumor/single_cell_RNAseq/201692_20210126_1_foxp3jmjd1c_mc205_tumour_wt_ko_treg/WT/outs/filtered_feature_bc_matrix")

KO.data <- as.data.frame(KO.data)
WT.data <- as.data.frame(WT.data)

for (i in 1:4105) {
   colnames(KO.data)[i] <- paste(colnames(KO.data)[i],"KO",i,sep = "-")  
}

for (i in 1:3905) {
  colnames(WT.data)[i] <- paste(colnames(WT.data)[i],"WT",i,sep = "-")  
}

KO.metadata<-data.frame(colnames(KO.data),rep("KO",4105))
WT.metadata<-data.frame(colnames(WT.data),rep("WT",3905))
colnames(KO.metadata)<-c("barcode","group")
colnames(WT.metadata)<-c("barcode","group")
pbmc.metadata<-rbind(KO.metadata,WT.metadata)
rownames(pbmc.metadata)<-pbmc.metadata[,1]
pbmc.data<-cbind(KO.data,WT.data)

pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k",meta.data = pbmc.metadata,min.cells = 3, min.features = 200)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^mt-")
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 10)
pbmc <- NormalizeData(pbmc)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
ElbowPlot(pbmc)
pbmc <- FindNeighbors(pbmc, dims = 1:20)
pbmc <- FindClusters(pbmc, resolution = 0.8)
pbmc <- RunUMAP(pbmc, dims = 1:20)
pbmc <- RunTSNE(pbmc, dims = 1:20)
DimPlot(pbmc, reduction = "umap")
DimPlot(pbmc, reduction = "umap",split.by = "group")
DimPlot(pbmc, reduction = "tsne")
DimPlot(pbmc, reduction = "tsne",split.by = "group")
#scaldata_pbmc<-as.data.frame(pbmc@assays[["RNA"]]@scale.data)
#scaldata_pbmc<-as.data.frame(t(scaldata_pbmc))
#library(ggplot2)
#library(ggpubr)
#ggplot(data = scaldata_pbmc,aes(x=Jmjd1c,y=Nrp1)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = scaldata_pbmc,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
#library(dplyr)
#scaldata_pbmc_new<-filter(scaldata_pbmc,Jmjd1c >0,Nrp1>0)
#ggplot(data = scaldata_pbmc_new,aes(x=Jmjd1c,y=Nrp1)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = scaldata_pbmc_new,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 

WT <- CreateSeuratObject(counts = WT.data, project = "WT3k",meta.data = WT.metadata,min.cells = 3, min.features = 200)
WT[["percent.mt"]] <- PercentageFeatureSet(WT, pattern = "^mt-")
VlnPlot(WT, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
WT <- subset(WT, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 10)
WT <- NormalizeData(WT)
WT <- FindVariableFeatures(WT, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(WT)
WT <- ScaleData(WT, features = all.genes)
WT <- RunPCA(WT, features = VariableFeatures(object = WT))
ElbowPlot(WT)
WT <- FindNeighbors(WT, dims = 1:20)
WT <- FindClusters(WT, resolution = 0.8)
WT <- RunUMAP(WT, dims = 1:20)
WT <- RunTSNE(WT, dims = 1:20)
DimPlot(WT, reduction = "umap")
DimPlot(WT, reduction = "umap",split.by = "group")
DimPlot(WT, reduction = "tsne")
DimPlot(WT, reduction = "tsne",split.by = "group")
scaldata_WT<-as.data.frame(WT@assays[["RNA"]]@scale.data)
scaldata_WT<-as.data.frame(t(scaldata_WT))
#library(ggplot2)
#library(ggpubr)
#ggplot(data = scaldata_WT,aes(x=Jmjd1c,y=Nrp1)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = scaldata_WT,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
#library(dplyr)
#scaldata_WT_new<-filter(scaldata_WT,Jmjd1c >0,Nrp1>0)
#ggplot(data = scaldata_WT_new,aes(x=Jmjd1c,y=Nrp1)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = scaldata_WT_new,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 

IL2_stat5<-read.table("g:/GSE98638/IL2_STAT5_symbol.txt",sep = "\t",header = TRUE)
IL6_stat3<-read.table("g:/GSE98638/IL6_STAT3_symbol.txt",sep = "\t",header = TRUE)

IL2_stat5<-IL2_stat5[2:200,]
IL6_stat3<-IL6_stat3[2:88,]

WT <- CellCycleScoring(WT, s.features = IL2_stat5, g2m.features = IL6_stat3, set.ident = FALSE)
IL2_stat5_list<-list(IL2_stat5)
IL6_stat3_list<-list(IL6_stat3)
WT <- AddModuleScore(WT,features = IL2_stat5_list,name = "IL2_stat5")
WT <- AddModuleScore(WT,features = IL6_stat3_list,name = "IL6_stat3")
JMJD1C<-select(scaldata_WT,starts_with("Jmjd1c"))
NRP1<-select(scaldata_WT,starts_with("Nrp1"))
Pdcd1<-select(scaldata_WT,starts_with("Pdcd1") & ends_with("Pdcd1"))
Ifng<-select(scaldata_WT,starts_with("Ifng") & ends_with("Ifng"))
IL2_stat5_score<-as.data.frame(WT$IL2_stat51)
IL6_stat3_score<-as.data.frame(WT$IL6_stat31)
data<-cbind(IL2_stat5_score,IL6_stat3_score,JMJD1C,Pdcd1,Ifng,NRP1)
colnames(data)<-c("IL2_stat5","IL6_stat3","JMJD1C","Pdcd1","Ifng","NRP1")
#library(corrplot)
#corrplot(matrix, method = "color")  

library(ggplot2)
library(ggpubr)
ggplot(data = data,aes(x=IL2_stat5,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new<-filter(data,IL2_stat5>0 & JMJD1C>0)
ggplot(data = data_new,aes(x=IL2_stat5,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=IL6_stat3,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new2<-filter(data,IL6_stat3>0 & JMJD1C>0)
ggplot(data = data_new2,aes(x=IL6_stat3,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new2,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=Pdcd1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new3<-filter(data,Pdcd1>0 & JMJD1C>0)
ggplot(data = data_new3,aes(x=Pdcd1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new3,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=Ifng,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new4<-filter(data,Ifng>0 & JMJD1C>0)
ggplot(data = data_new4,aes(x=Ifng,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new4,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=NRP1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new5<-filter(data,NRP1>0 & JMJD1C>0)
ggplot(data = data_new5,aes(x=NRP1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new5,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 



KO <- CreateSeuratObject(counts = KO.data, project = "KO3k",meta.data = KO.metadata,min.cells = 3, min.features = 200)
KO[["percent.mt"]] <- PercentageFeatureSet(KO, pattern = "^mt-")
VlnPlot(KO, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
KO <- subset(KO, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 10)
KO <- NormalizeData(KO)
KO <- FindVariableFeatures(KO, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(KO)
KO <- ScaleData(KO, features = all.genes)
KO <- RunPCA(KO, features = VariableFeatures(object = KO))
ElbowPlot(KO)
KO <- FindNeighbors(KO, dims = 1:20)
KO <- FindClusters(KO, resolution = 0.8)
KO <- RunUMAP(KO, dims = 1:20)
KO <- RunTSNE(KO, dims = 1:20)
DimPlot(KO, reduction = "umap")
DimPlot(KO, reduction = "umap",split.by = "group")
DimPlot(KO, reduction = "tsne")
DimPlot(KO, reduction = "tsne",split.by = "group")
scaldata_KO<-as.data.frame(KO@assays[["RNA"]]@scale.data)
scaldata_KO<-as.data.frame(t(scaldata_KO))

IL2_stat5<-read.table("g:/GSE98638/IL2_STAT5_symbol.txt",sep = "\t",header = TRUE)
IL6_stat3<-read.table("g:/GSE98638/IL6_STAT3_symbol.txt",sep = "\t",header = TRUE)

IL2_stat5<-IL2_stat5[2:200,]
IL6_stat3<-IL6_stat3[2:88,]

KO <- CellCycleScoring(KO, s.features = IL2_stat5, g2m.features = IL6_stat3, set.ident = FALSE)
IL2_stat5_list<-list(IL2_stat5)
IL6_stat3_list<-list(IL6_stat3)
KO <- AddModuleScore(KO,features = IL2_stat5_list,name = "IL2_stat5")
KO <- AddModuleScore(KO,features = IL6_stat3_list,name = "IL6_stat3")
JMJD1C<-select(scaldata_KO,starts_with("Jmjd1c"))
NRP1<-select(scaldata_KO,starts_with("Nrp1"))
Pdcd1<-select(scaldata_KO,starts_with("Pdcd1") & ends_with("Pdcd1"))
Ifng<-select(scaldata_KO,starts_with("Ifng") & ends_with("Ifng"))
IL2_stat5_score<-as.data.frame(KO$IL2_stat51)
IL6_stat3_score<-as.data.frame(KO$IL6_stat31)
data<-cbind(IL2_stat5_score,IL6_stat3_score,JMJD1C,Pdcd1,Ifng,NRP1)
colnames(data)<-c("IL2_stat5","IL6_stat3","JMJD1C","Pdcd1","Ifng","NRP1")
#library(corrplot)
#corrplot(matrix, method = "color")  

library(ggplot2)
library(ggpubr)
ggplot(data = data,aes(x=IL2_stat5,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new<-filter(data,IL2_stat5>0 & JMJD1C>0)
ggplot(data = data_new,aes(x=IL2_stat5,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=IL6_stat3,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new2<-filter(data,IL6_stat3>0 & JMJD1C>0)
ggplot(data = data_new2,aes(x=IL6_stat3,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new2,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=Pdcd1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new3<-filter(data,Pdcd1>0 & JMJD1C>0)
ggplot(data = data_new3,aes(x=Pdcd1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new3,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=Ifng,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new4<-filter(data,Ifng>0 & JMJD1C>0)
ggplot(data = data_new4,aes(x=Ifng,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new4,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
ggplot(data = data,aes(x=NRP1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
data_new5<-filter(data,NRP1>0 & JMJD1C>0)
ggplot(data = data_new5,aes(x=NRP1,y=JMJD1C)) + geom_point(color="blue",size=3.4) + stat_smooth(method = "lm",se=FALSE,size=1.5,color="red")+stat_cor(data = data_new5,method = "pearson") +  theme_set(theme_bw()) +  theme_set(theme_bw()) 
